-- Tạo bảng comment_likes (vì comments đã tồn tại)
create table public.comment_likes (
  id bigint generated by default as identity primary key,
  comment_id bigint references comments(id) on delete cascade,
  user_id uuid references auth.users(id) on delete cascade,
  created_at timestamp with time zone default now(),
  unique(comment_id, user_id)
);

-- Tạo indexes cho performance
create index comment_likes_comment_id_idx on comment_likes(comment_id);
create index comment_likes_user_id_idx on comment_likes(user_id);

-- Enable Row Level Security
alter table comment_likes enable row level security;

-- RLS Policies cho comment_likes
create policy "Users can view all comment likes" on comment_likes
  for select using (true);

create policy "Users can insert their own comment likes" on comment_likes
  for insert with check (auth.uid() = user_id);

create policy "Users can delete their own comment likes" on comment_likes
  for delete using (auth.uid() = user_id); 